// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoSqpm0fQbMcNdxEuQp0p-TWNAnGTBBcY',
    appId: '1:591513818417:web:1db7f059223e1a174a0c10',
    messagingSenderId: '591513818417',
    projectId: 'dartfire-193da',
    authDomain: 'dartfire-193da.firebaseapp.com',
    storageBucket: 'dartfire-193da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7xrowVBYAO4qr-WZz6LhvXCNN_hC9jK8',
    appId: '1:591513818417:android:c032ac925bd36dfd4a0c10',
    messagingSenderId: '591513818417',
    projectId: 'dartfire-193da',
    storageBucket: 'dartfire-193da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX0R_m9_vfudjfxTWH-bWFKGOFixJ4tTQ',
    appId: '1:591513818417:ios:a6adcd28d29d60994a0c10',
    messagingSenderId: '591513818417',
    projectId: 'dartfire-193da',
    storageBucket: 'dartfire-193da.appspot.com',
    iosClientId: '591513818417-9nk3avbu87294ch3era0lgt1bckm9ngd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX0R_m9_vfudjfxTWH-bWFKGOFixJ4tTQ',
    appId: '1:591513818417:ios:a6adcd28d29d60994a0c10',
    messagingSenderId: '591513818417',
    projectId: 'dartfire-193da',
    storageBucket: 'dartfire-193da.appspot.com',
    iosClientId: '591513818417-9nk3avbu87294ch3era0lgt1bckm9ngd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
